"""
AgentCore Runtime Agent: returns_agent_runtime
Generated by AgentCore MCP Server

This agent is ready to deploy to AgentCore Runtime with:
1. BedrockAgentCoreApp entrypoint
2. Memory integration
3. Gateway tools
4. Knowledge Base access
5. Custom tools
"""

import os
import json
from bedrock_agentcore.runtime import BedrockAgentCoreApp
from strands import Agent, tool
from strands.models import BedrockModel
from strands_tools import retrieve
from strands_tools import current_time
from strands.tools.mcp import MCPClient
from mcp.client.streamable_http import streamablehttp_client
import requests
from bedrock_agentcore.memory.integrations.strands.config import AgentCoreMemoryConfig, RetrievalConfig
from bedrock_agentcore.memory.integrations.strands.session_manager import AgentCoreMemorySessionManager
from datetime import datetime

# Constants
MODEL_ID = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
REGION = "us-west-2"
SESSION_ID = "default-session"
ACTOR_ID = "default-actor"

# Initialize app
app = BedrockAgentCoreApp()

print("="*80)
print("RETURNS AGENT RUNTIME - INITIALIZING")
print("="*80)

# Load configurations from files (fallback to env vars)
def load_config(filename, env_key=None):
    """Load config from file or environment variable"""
    try:
        with open(filename) as f:
            return json.load(f)
    except FileNotFoundError:
        if env_key:
            value = os.environ.get(env_key)
            if value:
                print(f"⚠️  {filename} not found, using env var {env_key}")
                return {env_key.lower(): value}
        print(f"⚠️  {filename} not found and no env var set")
        return {}

# Load Knowledge Base config
kb_config = load_config('kb_config.json', 'KNOWLEDGE_BASE_ID')
kb_id = kb_config.get('knowledge_base_id', os.environ.get('KNOWLEDGE_BASE_ID', 'YOUR_KB_ID_HERE'))
print(f"✓ Knowledge Base ID: {kb_id}")

# Load Memory config
memory_config = load_config('memory_config.json', 'MEMORY_ID')
MEMORY_ID = memory_config.get('memory_id', os.environ.get('MEMORY_ID'))
if MEMORY_ID:
    print(f"✓ Memory ID: {MEMORY_ID}")

# Load Gateway config
gateway_config = load_config('gateway_config.json', 'GATEWAY_URL')
GATEWAY_URL = gateway_config.get('gateway_url', os.environ.get('GATEWAY_URL'))
if GATEWAY_URL:
    print(f"✓ Gateway URL: {GATEWAY_URL}")

# Load Cognito config
cognito_config = load_config('cognito_config.json')
COGNITO_CLIENT_ID = cognito_config.get('client_id', os.environ.get('COGNITO_CLIENT_ID'))
COGNITO_CLIENT_SECRET = cognito_config.get('client_secret', os.environ.get('COGNITO_CLIENT_SECRET'))
COGNITO_DISCOVERY_URL = cognito_config.get('discovery_url', os.environ.get('COGNITO_DISCOVERY_URL'))
if all([COGNITO_CLIENT_ID, COGNITO_CLIENT_SECRET, COGNITO_DISCOVERY_URL]):
    print(f"✓ Cognito configured")

print("="*80)

# ============================================================================
# CUSTOM TOOLS
# ============================================================================

@tool
def check_return_eligibility(purchase_date: str, category: str) -> dict:
    """Check if an item is eligible for return.
    
    Args:
        purchase_date: Purchase date in YYYY-MM-DD format
        category: Product category (e.g., 'electronics', 'clothing', 'books')
    
    Returns:
        dict with 'eligible' (bool), 'reason' (str), 'days_remaining' (int)
    """
    try:
        purchase = datetime.strptime(purchase_date, '%Y-%m-%d')
        today = datetime.now()
        days_since_purchase = (today - purchase).days
        
        # Return windows by category
        return_windows = {
            'electronics': 30,
            'clothing': 30,
            'books': 30,
            'grocery': 7,
            'software': 30,
            'default': 30
        }
        
        window = return_windows.get(category.lower(), return_windows['default'])
        days_remaining = window - days_since_purchase
        
        if days_remaining > 0:
            return {
                'eligible': True,
                'reason': f'Item is within {window}-day return window',
                'days_remaining': days_remaining
            }
        else:
            return {
                'eligible': False,
                'reason': f'Return window of {window} days has expired',
                'days_remaining': 0
            }
    except ValueError:
        return {
            'eligible': False,
            'reason': 'Invalid date format. Use YYYY-MM-DD',
            'days_remaining': 0
        }

@tool
def calculate_refund_amount(original_price: float, condition: str, return_reason: str) -> dict:
    """Calculate refund amount based on item condition and reason.
    
    Args:
        original_price: Original purchase price
        condition: Item condition ('new', 'opened', 'used', 'damaged')
        return_reason: Reason for return ('defective', 'wrong_item', 'changed_mind', 'other')
    
    Returns:
        dict with 'refund_amount' (float), 'refund_percentage' (int), 'explanation' (str)
    """
    # Full refund for defective or wrong items
    if return_reason.lower() in ['defective', 'wrong_item']:
        return {
            'refund_amount': original_price,
            'refund_percentage': 100,
            'explanation': 'Full refund for defective or incorrect item'
        }
    
    # Condition-based refunds for other reasons
    refund_rates = {
        'new': 1.0,
        'opened': 0.9,
        'used': 0.7,
        'damaged': 0.5
    }
    
    rate = refund_rates.get(condition.lower(), 0.7)
    refund_amount = original_price * rate
    refund_percentage = int(rate * 100)
    
    return {
        'refund_amount': round(refund_amount, 2),
        'refund_percentage': refund_percentage,
        'explanation': f'{refund_percentage}% refund for {condition} condition item'
    }

@tool
def format_policy_response(policy_text: str, query_context: str = '') -> str:
    """Format policy information in a customer-friendly way.
    
    Args:
        policy_text: Raw policy text from knowledge base
        query_context: Optional context about what customer asked
    
    Returns:
        Formatted, customer-friendly policy explanation
    """
    # Add friendly header
    formatted = '📋 Return Policy Information\n'
    formatted += '=' * 40 + '\n\n'
    
    if query_context:
        formatted += f'Regarding: {query_context}\n\n'
    
    # Clean up and format the policy text
    lines = policy_text.strip().split('\n')
    for line in lines:
        line = line.strip()
        if line:
            # Add bullet points for list items
            if line.startswith('-') or line.startswith('•'):
                formatted += f'  {line}\n'
            else:
                formatted += f'{line}\n'
    
    formatted += '\n' + '=' * 40 + '\n'
    formatted += '💡 Tip: Contact customer service if you have questions!\n'
    
    return formatted

# ============================================================================
# GATEWAY HELPER FUNCTIONS
# ============================================================================

def get_cognito_token_with_scope(client_id, client_secret, discovery_url, scope):
    """Get Cognito bearer token with a specific OAuth scope"""
    try:
        # Extract token endpoint from discovery URL
        discovery_response = requests.get(discovery_url, timeout=10)
        token_endpoint = discovery_response.json()['token_endpoint']
        
        # Get token using client credentials flow
        response = requests.post(
            token_endpoint,
            data={
                'grant_type': 'client_credentials',
                'client_id': client_id,
                'client_secret': client_secret,
                'scope': scope
            },
            headers={'Content-Type': 'application/x-www-form-urlencoded'},
            timeout=10
        )
        
        response.raise_for_status()
        return response.json()["access_token"]
    except Exception as e:
        print(f"Error getting Cognito token: {e}")
        raise

def create_mcp_client():
    """Create MCP client for gateway access"""
    oauth_scopes = "gateway-api/read gateway-api/write"
    
    if not all([GATEWAY_URL, COGNITO_CLIENT_ID, COGNITO_CLIENT_SECRET, COGNITO_DISCOVERY_URL]):
        return None
    
    try:
        token = get_cognito_token_with_scope(
            COGNITO_CLIENT_ID,
            COGNITO_CLIENT_SECRET,
            COGNITO_DISCOVERY_URL,
            oauth_scopes
        )
        return MCPClient(
            lambda: streamablehttp_client(
                GATEWAY_URL,
                headers={"Authorization": f"Bearer {token}"},
            )
        )
    except Exception as e:
        print(f"Warning: Failed to create MCP client: {e}")
        return None

# System prompt
system_prompt = f"""Production returns assistant with full memory and gateway capabilities. Use the retrieve tool to access Amazon return policy documents for accurate information.

When using the retrieve tool, always pass these parameters:
- knowledgeBaseId: {kb_id}
- region: {REGION}
- text: the search query

You have access to:
- Gateway tools for external operations (like lookup_order)
- Customer conversation history and preferences through memory
- Knowledge base for return policy information
- Custom tools for return eligibility and refund calculations"""

@app.entrypoint
def invoke(payload, context=None):
    """AgentCore Runtime entrypoint"""
    try:
        print(f"\n{'='*80}")
        print("AGENT INVOCATION STARTED")
        print(f"{'='*80}")
        
        # Initialize model inside the function
        bedrock_model = BedrockModel(model_id=MODEL_ID, temperature=0.3)
        
        # Get session and actor info
        session_id = context.session_id if context else SESSION_ID
        actor_id = payload.get("actor_id", ACTOR_ID)
        
        print(f"Session ID: {session_id}")
        print(f"Actor ID: {actor_id}")
        
        # Configure memory
        memory_id = MEMORY_ID or os.environ.get("MEMORY_ID")
        if not memory_id:
            print("⚠️  Warning: MEMORY_ID not set, running without memory")
            session_manager = None
        else:
            print(f"✓ Configuring memory: {memory_id}")
            agentcore_memory_config = AgentCoreMemoryConfig(
                memory_id=memory_id,
                session_id=session_id,
                actor_id=actor_id,
                retrieval_config={
                    f"app/{actor_id}/semantic": RetrievalConfig(top_k=3),
                    f"app/{actor_id}/preferences": RetrievalConfig(top_k=3),
                    f"app/{actor_id}/{session_id}/summary": RetrievalConfig(top_k=2),
                }
            )
            
            session_manager = AgentCoreMemorySessionManager(
                agentcore_memory_config=agentcore_memory_config,
                region_name=REGION
            )
        
        # Build custom tools list
        custom_tools = [
            retrieve, 
            current_time, 
            check_return_eligibility, 
            calculate_refund_amount, 
            format_policy_response
        ]
        print(f"✓ Loaded {len(custom_tools)} custom tools")
        
        # Try to create MCP client for gateway tools
        mcp_client = create_mcp_client()
        
        if mcp_client:
            try:
                print("✓ Attempting to load gateway tools...")
                # Keep MCP client active during agent execution
                with mcp_client:
                    # Get gateway tools from MCP client
                    gateway_tools = list(mcp_client.list_tools_sync())
                    print(f"✓ Loaded {len(gateway_tools)} gateway tools")
                    
                    # Create agent with all tools
                    agent = Agent(
                        model=bedrock_model,
                        tools=custom_tools + gateway_tools,
                        system_prompt=system_prompt,
                        session_manager=session_manager
                    )
                    
                    user_input = payload.get("prompt", "")
                    print(f"User input: {user_input[:100]}...")
                    
                    response = agent(user_input)
                    result = response.message["content"][0]["text"]
                    
                    print(f"{'='*80}")
                    print("AGENT INVOCATION COMPLETED SUCCESSFULLY")
                    print(f"{'='*80}\n")
                    
                    return result
            except Exception as e:
                print(f"⚠️  Warning: Failed to use gateway tools: {e}")
                print("Falling back to agent without gateway tools")
        else:
            print("ℹ️  Gateway not configured, running without gateway tools")
        
        # Create agent without gateway tools (fallback)
        agent = Agent(
            model=bedrock_model,
            tools=custom_tools,
            system_prompt=system_prompt,
            session_manager=session_manager
        )
        
        user_input = payload.get("prompt", "")
        print(f"User input: {user_input[:100]}...")
        
        response = agent(user_input)
        result = response.message["content"][0]["text"]
        
        print(f"{'='*80}")
        print("AGENT INVOCATION COMPLETED SUCCESSFULLY")
        print(f"{'='*80}\n")
        
        return result
    
    except Exception as e:
        error_msg = f"Agent invocation failed: {str(e)}"
        print(f"\n{'='*80}")
        print("AGENT INVOCATION FAILED")
        print(f"{'='*80}")
        print(error_msg)
        import traceback
        traceback.print_exc()
        print(f"{'='*80}\n")
        return {"error": error_msg, "traceback": traceback.format_exc()}

if __name__ == "__main__":
    print("\n" + "="*80)
    print("STARTING AGENTCORE RUNTIME")
    print("="*80 + "\n")
    app.run()
